export const ERROR_CHECK_LIST_TYPE = {
  required: 'Bạn không được để trống',
  toUpperCase: 'Chữ cái đầu tiên phải viết hoa',
  minLength: 'yêu cầu tối thiểu ',
  dataTypeNumber: 'Ký tự cuối cùng phải là số',
  maxLength: 'yêu cầu tối đa',
  dataType: 'dataType',
  min: 'min',
  max: 'max',
  format: 'format',
  regEmail: 'Chưa đúng định dạng email',
  checkDate: 'Phải lớn hơn hoặc bằng ngày hôm nay',
  checkPw: 'Không khớp password',
  checkNumber: 'Phải là số',
  checkPrice: 'Giá giảm phải nhỏ hơn giá gốc',
  checkNegative: 'Không được nhỏ hơn hoặc bằng 0',
  checkTimeEnd: 'Ngày kết thúc không được nhỏ hơn ngày bắt đầu',
}
